// 2025-02-23/social-network/frontend/social-network-client/src/components/layout/layout/Layout.tsx
// components/layout/layout/Layout.tsx
import { useContext } from "react";
import { Outlet } from "react-router-dom";
import { AuthContext } from "../../auth/Auth";
import Followings from "../following/Following";
import Folowers from "../folowers/Folowers";
import Footer from "../footer/Footer";
import Header from "../header/Header";
import LoginPage from "../login/login";

// Utility function to check if the user is authenticated


export default function Layout() {
  // Redirect to /login if the user is not authenticated
  // if (!isAuthenticated()) {
  //   return <Navigate to="/login" replace />;
  // }

  const {jwt} = useContext(AuthContext)!;
const isAuthenticated: boolean = !!jwt;


  return (
    <div>
      {!isAuthenticated && (
        <>
          <LoginPage />
        </>
      )}

      {isAuthenticated && (
        <>
          <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[1fr_3fr] h-screen">
            <header className="col-span-2 row-start-1 bg-gray-100 border border-gray-300">
              <Header />
            </header>

            <aside className="col-start-1 row-start-2 bg-white border border-gray-300 p-4 h-full grid grid-rows-2 gap-4">
              <div className="overflow-y-auto">
                <Followings />
              </div>
              <div className="overflow-y-auto">
                <Folowers />
              </div>
            </aside>

            <main className="col-start-2 row-start-2 row-span-2 bg-gray-50 border border-gray-300 p-4">
              <div className="h-full overflow-y-auto">
                <Outlet />
              </div>
            </main>

            <footer className="col-span-2 row-start-4 bg-gray-800 h-5 text-white text-center py-4">
              <Footer />
            </footer>
          </div>
        </>
      )}
    </div>
  );
}

// 2025-03-30-agular/02-social-network-client/src/app/components/layout/layout/layout.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from "../header/header.component";
import { FooterComponent } from "../footer/footer.component";
import { FollowingComponent } from "../../follows/following/following.component";
import { FollowersComponent } from "../../follows/followers/followers.component";
import { RouterOutlet } from '@angular/router';
import { ProfileComponent } from "../../posts/profile/profile.component";

@Component({
  selector: 'app-layout',
  imports: [
    HeaderComponent,
    FooterComponent,
    FollowingComponent,
    FollowersComponent,
    RouterOutlet,
    ProfileComponent
],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent {

}

<div class="grid grid-cols-1 md:grid-cols-[1fr_3fr] grid-rows-[auto_1fr_auto] h-screen gap-4 p-4">
    <header class="md:col-span-2 border border-dashed border-rose-400 p-2">
      <app-header></app-header>
    </header>
  
    <aside class="hidden md:block border border-dashed border-rose-400 p-2">
      <app-following></app-following>
    </aside>
  
    <main class="border border-dashed border-rose-400 overflow-auto p-2">
      <router-outlet></router-outlet>
    </main>
  
    <aside class="hidden md:block border border-dashed border-rose-400 p-2">
      <app-followers></app-followers>
    </aside>
  
    <footer class="md:col-span-2 border border-dashed border-rose-400 p-2">
      <app-footer></app-footer>
    </footer>
  </div>
