// 2025-03-30-agular/02-social-network-client/src/app/components/layout/layout/layout.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from '../header/header.component';
import { FooterComponent } from '../footer/footer.component';
import { FollowingComponent } from '../../follows/following/following.component';
import { FollowersComponent } from '../../follows/followers/followers.component';
import { ProfileComponent } from '../../posts/profile/profile.component';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-layout',
  imports: [
    HeaderComponent,
    FooterComponent,
    FollowingComponent,
    FollowersComponent,
    ProfileComponent,
    RouterOutlet,
  ],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css',
})
export class LayoutComponent {}

<div id="grid" class="grid grid-cols-[1fr_3fr] grid-rows-[1fr_3fr_3fr_1fr] h-full">
    <header class="row-start-1 col-span-2 border border-dashed border-[color:lightcoral]">
      <app-header></app-header>
    </header>
    <aside class="row-start-2 col-start-1 border border-dashed border-[color:lightcoral]">
      <app-following></app-following>
    </aside>
    <aside class="row-start-3 col-start-1 border border-dashed border-[color:lightcoral]">
      <app-followers></app-followers>
    </aside>
    <main class="row-start-2 row-span-2 col-start-2 overflow-auto border border-dashed border-[color:lightcoral]">
      <app-profile></app-profile>
    </main>
    <footer class="row-start-4 col-span-2 border border-dashed border-[color:lightcoral]">
      <app-footer></app-footer>
    </footer>
  </div>

// 2025-01-07/social-network-client/src/components/layout/layout/Layout.tsx
import Folowers from '../folowers/Folowers';
import Followings from '../following/Following';
import Footer from '../footer/Footer';
import Header from '../header/Header';
import Routing from '../routing/Routing';
// import './Layout.css';
import { Navigate } from 'react-router-dom';

// Utility function to check if the user is authenticated
const isAuthenticated = (): boolean => {
    // Look for the presence of the 'auth' cookie
    return document.cookie.split('; ').some((cookie) => cookie.startsWith('auth='));
};
export default function Layout() {
    // Redirect to /login if the user is not authenticated
    if (!isAuthenticated()) {
      return <Navigate to="/login" />;
    }
  
    return (
      <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[1fr_3fr] h-screen">
  <header className="col-span-2 row-start-1 bg-gray-100 border border-gray-300">
    <Header />
  </header>

  <aside className="col-start-1 row-start-2 bg-white border border-gray-300 p-4 overflow-y-auto">
    <Followings />
  </aside>

  <aside className="col-start-1 row-start-3 bg-white border border-gray-300 p-4 overflow-y-auto">
    <Folowers />
  </aside>

  <main className="col-start-2 row-start-2 row-span-2 bg-gray-50 border border-gray-300 p-4">
    <div className="h-full overflow-y-auto">
      <Routing />
    </div>
  </main>

  <footer className="col-span-2 row-start-4 bg-gray-800 text-white text-center py-4">
    <Footer />
  </footer>
</div>
    );
  }
